# fly.toml app configuration file generated for pb-muzik-player on 2023-07-07T15:43:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pb-muzik-player"
primary_region = "ord"

[deploy]
  release_command = "npx prisma migrate deploy & npm run seed"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
